# Generated by Django 5.0.4 on 2024-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_create_date_course_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
